# Generated by Django 5.1.6 on 2025-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('bg', 'Bulgaria')], default='bg', max_length=20, verbose_name='country')),
                ('province', models.CharField(max_length=20, verbose_name='province')),
                ('town', models.CharField(max_length=20, verbose_name='town')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='number')),
                ('building', models.CharField(blank=True, max_length=10, null=True, verbose_name='building')),
                ('entrance', models.CharField(blank=True, max_length=5, null=True, verbose_name='entrance')),
                ('apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='apartment')),
            ],
        ),
    ]
