# Generated by Django 5.1.6 on 2025-04-28 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('message', models.TextField(verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('bg', 'Bulgaria')], default='bg', max_length=20, verbose_name='country')),
                ('province', models.CharField(max_length=20, verbose_name='province')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='number')),
                ('block', models.CharField(blank=True, max_length=20, null=True, verbose_name='block')),
                ('building', models.CharField(blank=True, max_length=10, null=True, verbose_name='building')),
                ('entrance', models.CharField(blank=True, max_length=5, null=True, verbose_name='entrance')),
                ('apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='apartment')),
                ('store', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
