# Generated by Django 5.2 on 2025-04-13 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('stores', '0002_remove_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='store',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
