# Generated by Django 5.1.6 on 2025-04-15 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 10, 52, 50, 105853, tzinfo=datetime.timezone.utc)),
        ),
    ]
