# Generated by Django 5.1.6 on 2025-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='town',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Plovdiv', max_length=20, verbose_name='city'),
            preserve_default=False,
        ),
    ]
