# Generated by Django 5.1.6 on 2025-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_address_town_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='block',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='block'),
        ),
    ]
