# Generated by Django 5.1.6 on 2025-04-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_address_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code'),
        ),
    ]
