# Generated by Django 5.1.6 on 2025-04-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('name_bg', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='name')),
                ('name_en', models.CharField(max_length=20, null=True, unique=True, verbose_name='name')),
                ('name_bg', models.CharField(max_length=20, null=True, unique=True, verbose_name='name')),
                ('color_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'color group',
                'verbose_name_plural': 'color groups',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'pattern',
                'verbose_name_plural': 'patterns',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='size')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'style',
                'verbose_name_plural': 'styles',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='item number')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('name_bg', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_bg', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount price')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True, verbose_name='content')),
                ('content_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='content')),
                ('content_bg', models.CharField(blank=True, max_length=100, null=True, verbose_name='content')),
                ('is_bestseller', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category', verbose_name='category')),
                ('color_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.colorgroup', verbose_name='color group')),
                ('linked_items', models.ManyToManyField(blank=True, to='items.item', verbose_name='linked items')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.pattern', verbose_name='pattern')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('at_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='at price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='items.item', verbose_name='item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='sales.onlineorder', verbose_name='order')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='items.size', verbose_name='size')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sales.cart', verbose_name='cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='items.item', verbose_name='item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='items.size', verbose_name='size')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.size')),
                ('store', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'verbose_name': 'stock',
                'verbose_name_plural': 'stock',
                'unique_together': {('item', 'store', 'size')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(related_name='items', through='items.Stock', to='items.size', verbose_name='sizes'),
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.ManyToManyField(blank=True, to='items.style', verbose_name='style'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('name_bg', models.CharField(blank=True, max_length=50, null=True, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='items.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.subcategory', verbose_name='subcategory'),
        ),
    ]
