# Generated by Django 5.1.6 on 2025-03-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size'], 'verbose_name': 'size', 'verbose_name_plural': 'sizes'},
        ),
    ]
