# Generated by Django 5.2 on 2025-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(related_name='items', through='items.Stock', to='items.size'),
        ),
    ]
