# Generated by Django 5.1.6 on 2025-04-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_sizes'),
        ('stores', '0002_remove_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
