# Generated by Django 5.1.6 on 2025-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_stock_translated_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='colorgroup',
            options={'ordering': ['name'], 'verbose_name': 'color group', 'verbose_name_plural': 'color groups'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'ordering': ['name'], 'verbose_name': 'pattern', 'verbose_name_plural': 'patterns'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name': 'subcategory', 'verbose_name_plural': 'subcategories'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total price'),
        ),
    ]
