# Generated by Django 5.1.6 on 2025-04-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_size_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
