# Generated by Django 5.1.6 on 2025-06-11 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_category_options_alter_colorgroup_options_and_more'),
        ('sales', '0003_alter_onlineorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='sales.onlineorder', verbose_name='order'),
        ),
    ]
