# Generated by Django 5.1.6 on 2025-04-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_stock_store'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sales.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('size', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.size')),
            ],
        ),
    ]
