# Generated by Django 5.1.6 on 2025-06-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='additional information'),
        ),
    ]
