# Generated by Django 5.1.6 on 2025-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='additional_info_bg',
            field=models.TextField(blank=True, null=True, verbose_name='additional information'),
        ),
        migrations.AddField(
            model_name='item',
            name='additional_info_en',
            field=models.TextField(blank=True, null=True, verbose_name='additional information'),
        ),
    ]
