# Generated by Django 5.1.6 on 2025-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='at_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
