# Generated by Django 5.1.6 on 2025-07-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_item_additional_info_bg_item_additional_info_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
