# Generated by Django 5.1.6 on 2025-04-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_orderitem_at_price'),
        ('sales', '0012_alter_onlineorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='sales.cart', verbose_name='cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='items.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='items.size', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_bg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='name_bg',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='colorgroup',
            name='name_en',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.colorgroup', verbose_name='color group'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content_bg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='item number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='linked_items',
            field=models.ManyToManyField(blank=True, to='items.item', verbose_name='linked items'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_bg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.pattern', verbose_name='pattern'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(related_name='items', through='items.Stock', to='items.size', verbose_name='sizes'),
        ),
        migrations.AlterField(
            model_name='item',
            name='style',
            field=models.ManyToManyField(blank=True, to='items.style', verbose_name='style'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.subcategory', verbose_name='subcategory'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='at_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='at price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='items.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='sales.onlineorder', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='items.size', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='items.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_bg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
    ]
