# Generated by Django 5.1.6 on 2025-10-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_itemcollection_item_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcollection',
            options={'verbose_name': 'collection'},
        ),
    ]
