# Generated by Django 5.1.6 on 2025-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='id',
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
