# Generated by Django 5.1.6 on 2025-10-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_itemcollection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcollection',
            options={'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
    ]
