# Generated by Django 5.1.6 on 2026-01-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_itemcollection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='price eur'),
        ),
    ]
