# Generated by Django 5.1.6 on 2026-01-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_price_eur'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount price'),
        ),
    ]
