# Generated by Django 5.1.6 on 2026-01-01 13:46
from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations

EURO_RATE = Decimal('1.95583')


def forward(apps, schema_editor):
    Item = apps.get_model('items', 'Item')

    batch = []

    qs = Item.objects.all().only('pk', 'price', 'discount_price')

    for obj in qs.iterator(chunk_size=1000):
        obj.price_eur = (obj.price / EURO_RATE).quantize(Decimal("0.01"), ROUND_HALF_UP)

        if obj.discount_price:
            obj.discount_price_eur = (obj.discount_price / EURO_RATE).quantize(Decimal("0.01"), ROUND_HALF_UP)
        else:
            obj.discount_price_eur = None

        batch.append(obj)

        if len(batch) >= 1000:
            Item.objects.bulk_update(batch, ['price_eur', 'discount_price_eur'])
            batch.clear()

    if batch:
        Item.objects.bulk_update(batch, ['price_eur', 'discount_price_eur'])


def backward(apps, schema_editor):
    Item = apps.get_model('items', 'Item')
    Item.objects.update(price_eur=0, discount_price_eur=None)


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_discount_price_eur'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
