# Generated by Django 5.1.6 on 2026-01-13 13:13
from decimal import Decimal

from django.db import migrations
from django.db.models import F, Case, When, Value
from django.db.models.functions import Round

EURO_RATE = Decimal('1.95583')


def forward(apps, schema_editor):
    Item = apps.get_model('items', 'Item')

    Item.objects.update(price=F('price_eur'), discount_price=F('discount_price_eur'))


def backward(apps, schema_editor):
    Item = apps.get_model('items', 'Item')

    Item.objects.update(
        price=Round(F('price') * Value(EURO_RATE), precision=2),
        discount_price=Case(
            When(discount_price__isnull=True, then=Value(None)),
            default=Round(F('discount_price') * Value(EURO_RATE), precision=2)
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_backfill_eur_prices'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
