# Generated by Django 5.1.6 on 2026-01-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_recalculate_price_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_price_eur',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_eur',
        ),
    ]
