# Generated by Django 6.0.2 on 2026-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_remove_item_discount_price_eur_remove_item_price_eur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(related_name='items', through='items.Stock', through_fields=('item', 'size'), to='items.size', verbose_name='sizes'),
        ),
    ]
