# Generated by Django 6.0.2 on 2026-05-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_alter_item_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_bestseller',
        ),
        migrations.AddField(
            model_name='item',
            name='starting_size',
            field=models.CharField(default='40', max_length=5),
        ),
    ]
