# Generated by Django 6.0.2 on 2026-09-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_orderrefunditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='canceled'),
        ),
    ]
