# Generated by Django 5.1.6 on 2025-05-20 08:01

import fashionShop.pictures.utils.cloudflare
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image_r2',
            field=models.ImageField(blank=True, null=True, upload_to=fashionShop.pictures.utils.cloudflare.image_file_upload_handler),
        ),
    ]
