# Generated by Django 5.1.6 on 2025-03-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_alter_picture_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['is_main']},
        ),
        migrations.AddField(
            model_name='picture',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
