# Generated by Django 5.1.6 on 2025-06-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picture_image_r2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-is_main', 'is_detail', 'created_at']},
        ),
    ]
