# Generated by Django 5.1.6 on 2025-06-22 13:17

import django.db.models.deletion
import fashionShop.pictures.utils.cloudflare
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_alter_picture_options'),
        ('reviews', '0003_alter_review_options_review_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=fashionShop.pictures.utils.cloudflare.review_image_upload_handler)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='reviews.review')),
            ],
        ),
    ]
