# Generated by Django 6.0.2 on 2026-06-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_reviewpicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
    ]
