# Generated by Django 5.1.6 on 2025-03-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_picture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='name',
        ),
    ]
