# Generated by Django 5.1.6 on 2025-03-15 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_remove_picture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 15, 12, 18, 57, 530854, tzinfo=datetime.timezone.utc)),
        ),
    ]
