# Generated by Django 5.1.6 on 2025-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_picture_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
