# Generated by Django 5.1.6 on 2025-03-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_alter_picture_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['is_main', 'created_at']},
        ),
    ]
