# Generated by Django 5.1.6 on 2025-03-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_alter_picture_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='is_detail',
            field=models.BooleanField(default=False),
        ),
    ]
