# Generated by Django 5.1.6 on 2025-03-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_picture_description_picture_is_detail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-is_main', 'is_detail', '-created_at']},
        ),
    ]
