# Generated by Django 5.1.6 on 2025-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0011_alter_picture_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
