# Generated by Django 5.1.6 on 2025-04-28 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='last name')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=30, null=True, verbose_name='e-mail')),
                ('shipping_method', models.CharField(blank=True, choices=[('spof', 'SPEEDY office'), ('spad', 'SPEEDY address'), ('ecof', 'ECONT office'), ('ecad', 'ECONT address')], max_length=5, null=True, verbose_name='shipping method')),
                ('town', models.CharField(blank=True, max_length=30, null=True, verbose_name='town')),
                ('office', models.CharField(blank=True, max_length=100, null=True, verbose_name='office')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('order_code', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_orders', to='common.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
