# Generated by Django 5.1.6 on 2025-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineorder',
            options={'verbose_name': 'Online Order', 'verbose_name_plural': 'Online Orders'},
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(choices=[('pnd', 'pending'), ('cnf', 'confirmed'), ('cnl', 'canceled'), ('snt', 'sent'), ('rjt', 'rejected'), ('abd', 'abandoned'), ('cmp', 'completed'), ('rpl', 'replaced'), ('rfn', 'refunded')], default='pnd', max_length=3),
        ),
    ]
