# Generated by Django 5.1.6 on 2025-05-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_onlineorder_options_onlineorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(blank=True, choices=[('pnd', 'pending'), ('cnf', 'confirmed'), ('cnl', 'canceled'), ('snt', 'sent'), ('rjt', 'rejected'), ('abd', 'abandoned'), ('cmp', 'completed'), ('rpl', 'replaced'), ('rfn', 'refunded')], default='pnd', max_length=3),
        ),
    ]
