# Generated by Django 5.1.6 on 2025-04-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_address_user'),
        ('sales', '0002_onlineorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_orders', to='common.address'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='phone',
            field=models.CharField(default=359886531811, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('spof', 'SPEEDY office'), ('spad', 'SPEEDY, address'), ('ecof', 'ECONT office'), ('ecad', 'ECONT address')], max_length=5, null=True),
        ),
    ]
