# Generated by Django 5.1.6 on 2025-06-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_onlineorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
