# Generated by Django 5.1.6 on 2025-04-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_onlineorder_address_onlineorder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='town',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
