# Generated by Django 5.1.6 on 2025-04-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_onlineorder_office_onlineorder_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
