# Generated by Django 5.1.6 on 2025-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_onlineorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
