# Generated by Django 5.1.6 on 2025-04-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_onlineorder_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='last name'),
        ),
    ]
