# Generated by Django 5.1.6 on 2025-06-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_onlineorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='e-mail'),
        ),
    ]
