# Generated by Django 5.1.6 on 2025-08-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_onlineorder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='bisoft_report_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='town',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
