# Generated by Django 5.1.6 on 2025-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_onlineorder_first_name_onlineorder_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='office'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('spof', 'SPEEDY office'), ('spad', 'SPEEDY, address'), ('ecof', 'ECONT office'), ('ecad', 'ECONT address')], max_length=5, null=True, verbose_name='shipping method'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='town',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='town'),
        ),
    ]
