# Generated by Django 5.1.6 on 2025-04-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_onlineorder_office_alter_onlineorder_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True, verbose_name='e-mail'),
        ),
    ]
