# Generated by Django 5.1.6 on 2025-12-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_onlineorder_bisoft_report_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='send_message',
            field=models.BooleanField(default=True),
        ),
    ]
