# Generated by Django 5.1.6 on 2026-01-20 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ipaddress'),
        ('sales', '0008_onlineorder_send_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ipaddress'),
        ),
    ]
