# Generated by Django 5.1.6 on 2025-04-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_onlineorder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('spof', 'SPEEDY office'), ('spad', 'SPEEDY address'), ('ecof', 'ECONT office'), ('ecad', 'ECONT address')], max_length=5, null=True, verbose_name='shipping method'),
        ),
    ]
