# Generated by Django 5.1.6 on 2025-04-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_onlineorder_memo_alter_onlineorder_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineorder',
            name='order_code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
