# Generated by Django 6.0.2 on 2026-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_onlineorder_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
