# Generated by Django 5.1.6 on 2025-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_onlineorder_order_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineorder',
            name='memo',
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
