# Generated by Django 6.0.2 on 2026-06-28 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_onlineorder_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlineorder',
            options={'ordering': ['-pk'], 'verbose_name': 'Online Order', 'verbose_name_plural': 'Online Orders'},
        ),
        migrations.CreateModel(
            name='OnlineRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pnd', 'pending'), ('rcv', 'received'), ('pid', 'paid'), ('cnl', 'canceled')], default='pnd', max_length=3)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.onlineorder')),
            ],
            options={
                'verbose_name': 'Online Refund',
                'verbose_name_plural': 'Online Refunds',
            },
        ),
    ]
