# Generated by Django 5.1.6 on 2025-04-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_contactmessage_email_and_more'),
        ('sales', '0011_remove_onlineorder_memo_onlineorder_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_orders', to='common.address'),
        ),
    ]
