# Generated by Django 6.0.2 on 2026-06-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_onlineorder_options_onlinerefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinerefund',
            name='refund_all',
            field=models.BooleanField(default=True, verbose_name='refund_all'),
        ),
    ]
