# Generated by Django 6.0.2 on 2026-09-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_onlinerefund_refund_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinerefund',
            name='status',
            field=models.CharField(choices=[('pnd', 'pending'), ('rcv', 'received'), ('pid', 'paid out'), ('cnl', 'canceled')], default='pnd', max_length=3),
        ),
    ]
