version: '3.8'

services:
  app:
    build: .
    image: fashion-shop-image
    command: gunicorn fashionShop.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --keep-alive 5
    container_name: fashion-shop-container
    ports:
      - '8000:8000'
    volumes:
      - staticfiles_volume:/app/staticfiles
      - media_volume:/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles_volume:/app/staticfiles
      - media_volume:/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - app
    restart: always

  db:
    image: postgres:16
    container_name: vs-postgres-container
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-container
    restart: always

  celery:
    build: .
    image: fashion-shop-image
    container_name: celery-worker
    command: celery -A fashionShop worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    restart: always

volumes:
  postgres_data:
  staticfiles_volume:
  media_volume:
