# Generated by Django 5.1.6 on 2025-04-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='accepted_marketing_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='accepted_marketing_emails_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='accepted_privacy_policy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='accepted_privacy_policy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
