# Generated by Django 5.1.6 on 2025-06-22 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=100, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5, message='Please write something.')], verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='The review score cannot be below 1.'), django.core.validators.MaxValueValidator(5, message='The review score cannot be above 5.')], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
    ]
