server {
    listen 80;
    server_name vilistil.bg www.vilistil.bg;

    # Serve static files
    location /static/ {
        alias /app/staticfiles/;
        access_log off;
        expires 30d;
    }

    # Serve media files
    location /media/ {
        alias /media/;
        access_log off;
        expires 30d;
    }

    # Proxy pass to Gunicorn app server
    location / {
        proxy_pass http://app:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Optional: better timeout configs
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }
}
