name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_HOST_DEV: ${{ secrets.DB_HOST_DEV }}
      DB_PORT: ${{ secrets.DB_PORT }}
      CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      ADMIN_URL: ${{ secrets.ADMIN_URL }}
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
      CLOUDFLARE_R2_BUCKET: ${{ secrets.CLOUDFLARE_R2_BUCKET }}
      CLOUDFLARE_R2_ACCESS_TOKEN_VALUE: ${{ secrets.CLOUDFLARE_R2_ACCESS_TOKEN_VALUE }}
      CLOUDFLARE_R2_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
      CLOUDFLARE_R2_SECRET_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
      CLOUDFLARE_R2_BUCKET_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_BUCKET_ENDPOINT }}
      SPEEDY_USERNAME: ${{ secrets.SPEEDY_USERNAME }}
      SPEEDY_PASSWORD: ${{ secrets.SPEEDY_PASSWORD }}
      ECONT_USERNAME: ${{ secrets.ECONT_USERNAME }}
      ECONT_PASSWORD: ${{ secrets.ECONT_PASSWORD }}
      INFOBIP_URL: ${{ secrets.INFOBIP_URL }}
      INFOBIP_API_KEY: ${{ secrets.INFOBIP_API_KEY }}
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install system deps for xmlsec
      run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libxml2-dev libxmlsec1-dev libxmlsec1-openssl
    - name: Install Dependencies
      working-directory: fashionShop
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: fashionShop
      run: python manage.py test
