# Generated by Django 5.1.6 on 2025-03-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='linked_items',
            field=models.ManyToManyField(blank=True, null=True, to='items.item'),
        ),
    ]
