# Generated by Django 5.1.6 on 2025-03-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_linked_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('name_en', models.CharField(max_length=20, null=True, unique=True)),
                ('name_bg', models.CharField(max_length=20, null=True, unique=True)),
                ('color_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pattern',
            options={'verbose_name': 'pattern', 'verbose_name_plural': 'patterns'},
        ),
        migrations.AddField(
            model_name='item',
            name='color_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.colorgroup'),
        ),
    ]
