# Generated by Django 5.1.6 on 2025-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_colorgroup_alter_pattern_options_item_color_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='linked_items',
            field=models.ManyToManyField(blank=True, to='items.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.ManyToManyField(blank=True, to='items.style'),
        ),
    ]
