# Generated by Django 5.1.6 on 2025-03-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_stock_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorgroup',
            options={'verbose_name': 'color group', 'verbose_name_plural': 'color groups'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'size', 'verbose_name_plural': 'sizes'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'stock', 'verbose_name_plural': 'stock'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'verbose_name': 'style', 'verbose_name_plural': 'styles'},
        ),
    ]
